  openhab:
    image: "openhab/openhab:latest"
    container_name: openhab
    restart: unless-stopped
    network_mode: host
    # networks:
    #   - hosts_nw
#    cap_add:
#      - NET_ADMIN
#      - NET_RAW
    ports: # Changing this won't do anything. Change the port below under environment. Ensure values are synced
    - "4050:4050"
    - "4051:4051"
    - "8080:8080"
    - "9443:8443"
    - "5555:5555"
    - "9125:9125"
    - "9126:9126"
    - "8181:8181"
    - "9292:9292"
    - "2000:2000"
    - "2001:2001"
    - "2010:2010"
    - "8701:8701"
    - "8101:8101"
    - "43439:43439"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volumes/openhab/addons:/openhab/addons"
      - "./volumes/openhab/conf:/openhab/conf"
      - "./volumes/openhab/userdata:/openhab/userdata"
    environment:
      - OPENHAB_HTTP_PORT=4050
      - OPENHAB_HTTPS_PORT=4051
      - EXTRA_JAVA_OPTS=-Duser.timezone=Etc/UTC"
#    # The command node is very important. It overrides
#    # the "gosu openhab tini -s ./start.sh" command from Dockerfile and runs as root!
#    command: "tini -s ./start.sh server"
#    logging:
#      options:
#        max-size: "5m"
#        max-file: "3"
